[package]
name = "kafka-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
kafka = "0.9"
tokio = { version = "1", features = ["full"] }
futures = "0.3"